services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      PYTHONPATH: /app
    env_file:
      - .env
    command: >
      python run.py
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully

  alembic:
    build: .
    volumes:
      - ./:/app
    environment:
      PYTHONPATH: /app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      alembic upgrade head

  db:
    # Постгрес БД:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Kyiv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db_test:
    profiles: ["test"]
    image: postgres:16
    environment:
      TZ: Europe/Kyiv
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  tests:
    profiles: ["test"]
    build: .
    volumes:
      - ./:/app
    environment:
      PYTHONPATH: /app
    env_file:
      - .env.test
    depends_on:
      db_test:
        condition: service_healthy
    command: >
      pytest -q

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

volumes:
  postgres_data:
